[book]
title = "Legend SRD"
authors = ["Lawrence Whitaker", "Pete Nash", "Gareth Hanrahan"]
language = "pt-BR"
src = "src"

[output.html]
default-theme = "rust"
preferred-dark-theme = "rust"
mathjax-support = true
fold = { enable = true, level = 0 }
git-repository-url = "https://github.com/nerun/legend-srd"

[build]
build-dir = "docs"
